version: '3'

services:


  redis:
    image: redis:4.0.5-alpine
    ports: 
      - '6379:6379'

  calculator:
    build: ./
    depends_on:
      - 'redis'
    links: 
      - redis
    ports: 
      - '80:3002'
 
    