version: '3'

services:

  database:
    image: mongo:latest

  redis:
    image: redis:4.0.5-alpine
    ports: 
      - '6379:6379'

  calculator:
    build: ./
    depends_on:
      - 'database'
      - 'redis'
    links: 
      - redis
    environment: 
      REDIS_URL: redis
    ports: 
      - '8080:3002'
    